# Default values for tango-base.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"

global:
  minikube: false
  tango_host: databaseds-tango-base-{{.Release.Name}}:10000
  retry:
  - "--sleep=1"
  - "--tries=100"

homeDir: /home/ubuntu
system: SW-infrastructure
subsystem: ska-tango-base
telescope: SKA-mid

labels:
  app: ska-tango-images
annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG

dsconfig:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.2
    pullPolicy: IfNotPresent

itango:
  enabled: false
  component: itango-console
  function: generic-tango-console
  domain: interactive-testing
  intent: enabling
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-itango
    tag: 9.3.6
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m     # 00m = 0.1 CPU
      memory: 128Mi # 128Mi = 0.125 GB mem
      ephemeral-storage: 512Mi
    limits:
      cpu: 100m     # 00m = 0.1 CPU
      memory: 128Mi # 128Mi = 0.125 GB mem
      ephemeral-storage: 512Mi

databaseds:
  component: databaseds
  function: tangodb-interface
  domain: tango-configuration
  intent: production
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-cpp-alpine
    tag: 0.2.12
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m     # 100m = 0.1 CPU
      memory: 128Mi # 128Mi = 0.125 GB mem
      ephemeral-storage: 512Mi
    limits:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 1Gi
  livenessProbe:
    enabled: false
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    enabled: false
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

deviceServers:
  - name: tangotest
    function: tango-test
    domain: tango-base
    command: "/usr/local/bin/TangoTest"
    instances: ["test"]
    depends_on:
    - device: sys/database/2
    environment_variables: []
    server:
      name: "TangoTest"
      instances:
      - name: "test"
        classes: 
        - name: "TangoTest"
          devices: 
          - name: "sys/tg_test/1"
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-java
      tag: 9.3.5
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 200m     # 200m = 0.2 CPU
        memory: 256Mi # 256Mi = 0.25 GB mem
        ephemeral-storage: 1Gi
      limits:
        cpu: 500m     # 500m = 0.5 CPU
        memory: 512Mi # 512Mi = 0.5 GB mem
        ephemeral-storage: 1Gi

tangodb:
  enabled: true
  use_pv: false
  component: tangodb
  function: tango-device-configuration
  domain: tango-configuration
  intent: production
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-db
    tag: 10.4.13
    pullPolicy: IfNotPresent
  db:
    rootpw: secret
    db: tango
    user: tango
    password: tango
  resources:
    requests:
      cpu: 100m     # 100m = 0.1 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 1Gi
    limits:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 2Gi
  livenessProbe:
    enabled: false
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    enabled: false
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

jive:
  enabled: false
  component: jive-gui
  function: generic-tango-jive-gui
  domain: interactive-testing
  intent: enabling
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-java
    tag: 9.3.5
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 256Mi
    limits:
      cpu: 500m     # 500m = 0.5 CPU
      memory: 512Mi # 512Mi = 0.5 GB mem
      ephemeral-storage: 256Mi

vnc:
  enabled: false
  component: vnc-gui
  function: generic-tango-vnc-gui
  domain: interactive-testing
  intent: enabling
  nodeport_enabled: false
  nodeport_vnc: 32081
  nodeport_novnc: 32082
  replicas: 3
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-vnc
    tag: 0.1.4
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m     # 100m = 0.1 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 256Mi
    limits:
      cpu: 100m     # 100m = 0.1 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 256Mi

tangorest:
  enabled: false
  replicas: 3
  component: tango-rest
  function: tango-http-interface
  domain: tango-configuration
  intent: enabling
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-rest
    tag: 1.14.5
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m     # 100m = 0.1 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 256Mi
    limits:
      cpu: 200m     # 100m = 0.1 CPU
      memory: 512Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 512Mi

logviewer:
  enabled: false
  component: logviewer
  function: tango-log-inspection
  domain: interactive-testing
  intent: enabling
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-java
    tag: 9.3.5
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m     # 100m = 0.1 CPU
      memory: 128Mi # 128Mi = 0.125 GB mem
      ephemeral-storage: 256Mi
    limits:
      cpu: 100m     # 100m = 0.1 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 256Mi

# Configure Ingress resource that allow you to access the Tango REST API
ingress:
  enabled: true
  nginx: true

nodeSelector: {}

affinity: {}

tolerations: []
