{{ $localchart := . }}

{{ range $key, $deviceserver := .Values.deviceServers }}

{{ if $key }}

{{ $context := dict "name" $key "deviceserver" $deviceserver "image" $deviceserver.image "local" $localchart }}

{{ template "tango-util.multidevice-config.tpl" $context }}

{{ template "tango-util.multidevice-sacc-role.tpl" $context }}

{{ template "tango-util.multidevice-job.tpl" $context }}

{{ template "tango-util.multidevice-svc.tpl" $context }}

{{ end }}

{{ end }} # deviceservers


## old version
# {{ $localchart := . }}

# {{ range $deviceserver := .Values.deviceServers }}

# {{ range $instance := $deviceserver.instances }}

# {{ $context := dict "deviceserver" $deviceserver "image" $deviceserver.image "local" $localchart "instance" $instance }}

# {{ template "tango-util.deviceserver.tpl" $context }}

# {{ end }}

# {{ end }} # deviceservers
