{{ $localchart := . }}

{{ range $deviceserver := .Values.deviceServers }}

{{ $context := dict "deviceserver" $deviceserver "image" $deviceserver.image "local" $localchart }}

{{ template "tango-util.multidevice-config.tpl" $context }}

{{ template "tango-util.multidevice-sacc-role.tpl" $context }}

{{ template "tango-util.multidevice-job.tpl" $context }}

{{ template "tango-util.multidevice-svc.tpl" $context }}

{{ end }} # deviceservers
