{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rest-api-{{ template "tango-base.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 4 }}
    component: {{ .Values.tangorest.component }}
    function: {{ .Values.tangorest.function }}
    domain: {{ .Values.tangorest.domain }}
    intent: {{ .Values.tangorest.intent }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
      traefik.ingress.kubernetes.io/request-modifier: "ReplacePathRegex: /{{ .Release.Namespace }}/(.*) /$1"
{{ toYaml (coalesce .Values.global.annotations .Values.annotations "annotations:none") | indent 6 }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /{{ .Release.Namespace }}/tango/rest/
            backend:
              serviceName:  {{ template "tango-base.name" . }}-{{ .Values.tangorest.component }}
              servicePort: 8080
{{- if .Values.ingress.tls.enabled }}
  tls:
    - secretName: {{ tpl .Values.ingress.tls.secretname . }}
      hosts:
        - {{ tpl .Values.ingress.hostname . }}
{{- end -}}

{{- if .Values.ingress.tls.enabled }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .Values.ingress.tls.secretname . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 4 }}
    component: {{ .Values.tangorest.component }}
    function: {{ .Values.tangorest.function }}
    domain: {{ .Values.tangorest.domain }}
    intent: {{ .Values.tangorest.intent }}
type: kubernetes.io/tls
data:
{{ (tpl (.Files.Glob "secrets/tls.*").AsSecrets . ) | indent 2  }}

{{- end -}}
{{- end -}}
