{{ if .Values.jive.enabled }}
---

apiVersion: v1
kind: Pod
metadata:
  name: {{ template "tango-base.name" . }}-{{ .Values.jive.component }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tango-base.labels" . | indent 4 }}
    component: {{ .Values.jive.component }}
    function: {{ .Values.jive.function }}
    domain: {{ .Values.jive.domain }}
    intent: {{ .Values.jive.intent }}
spec:
  containers:
  - name: jive
    image: "{{ .Values.jive.image.registry }}/{{ .Values.jive.image.image }}:{{ .Values.jive.image.tag }}"
    imagePullPolicy: "{{ .Values.jive.image.pullPolicy }}"
    command:
      - /usr/local/bin/wait-for-it.sh
      - "{{ include "tango-base.dbservice-name" . }}:10000"
      - --timeout=30
      - --strict
      - --
      - /usr/local/bin/jive
    env:
    - name: XAUTHORITY
      value: "/tmp/.Xauthority"
    - name: DISPLAY
      value: "{{ .Values.display }}"
    - name: TANGO_HOST
      value: "{{ include "tango-base.dbservice-name" . }}:10000"
    volumeMounts:
      - name: xauthority
        mountPath: /tmp/.Xauthority
        readOnly: true
    resources:
{{ toYaml .Values.jive.resources | indent 6 }}
  volumes:
    - name: xauthority
      hostPath:
        path: {{ .Values.homeDir }}/.Xauthority
  restartPolicy: Always
{{- with .Values.nodeSelector }}
  nodeSelector:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.affinity }}
  affinity:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.tolerations }}
  tolerations:
{{ toYaml . | indent 4 }}
{{- end }}

{{ end }}