{{ if .Values.tangorest.enabled }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "tango-base.name" . }}-{{ .Values.tangorest.component }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml .Values.global.labels | indent 4 }}
    component: {{ .Values.tangorest.component }}
    function: {{ .Values.tangorest.function }}
    domain: {{ .Values.tangorest.domain }}
    intent: {{ .Values.tangorest.intent }}
spec:
  type: NodePort
  ports:
  - name: rest
    port: 8080
  selector:
{{ toYaml .Values.global.labels | indent 4 }}
    component: {{ .Values.tangorest.component }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "tango-base.name" . }}-{{ .Values.tangorest.component }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml .Values.global.labels | indent 4 }}
    component: {{ .Values.tangorest.component }}
    function: {{ .Values.tangorest.function }}
    domain: {{ .Values.tangorest.domain }}
    intent: {{ .Values.tangorest.intent }}
{{ if (.Values.global.annotations) }}
  annotations:
{{ toYaml .Values.global.annotations | indent 4 }}
{{ end }}
spec:
  selector:
    matchLabels:
{{ toYaml .Values.global.labels | indent 6 }}
      component: {{ .Values.tangorest.component }}
      function: {{ .Values.tangorest.function }}
      domain: {{ .Values.tangorest.domain }}
      intent: {{ .Values.tangorest.intent }}
  replicas: {{ .Values.tangorest.replicas }}
  template:
    metadata:
      labels:
{{ toYaml .Values.global.labels | indent 8 }}
        component: {{ .Values.tangorest.component }}
        function: {{ .Values.tangorest.function }}
        domain: {{ .Values.tangorest.domain }}
        intent: {{ .Values.tangorest.intent }}
{{ if (.Values.global.annotations) }}
      annotations:
{{ toYaml .Values.global.annotations | indent 8 }}
{{ end }}
    spec:
      {{- if .Values.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.pullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      containers:
      - name: tango-rest
        image: "{{ .Values.tangorest.image.registry }}/{{ .Values.tangorest.image.image }}:{{ .Values.tangorest.image.tag }}"
        imagePullPolicy: {{ .Values.tangorest.image.pullPolicy }}
        command:
          - /bin/bash
        args:
          - "-c"
          - >
            /usr/local/bin/wait-for-it.sh
            {{ .Values.global.tango_host }}
            --timeout=30
            --strict
            --
            /usr/bin/supervisord --configuration /etc/supervisor/supervisord.conf
        env:
        - name: TANGO_HOST
          value: "{{ .Values.global.tango_host }}"
        - name: JAVA_OPTS
          value: "-Xmx4G -Xshare:off -XX:+UseG1GC -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5009"
        ports:
        - name: rest
          containerPort: 8080
          protocol: TCP
        resources:
{{ toYaml .Values.tangorest.resources | indent 10 }}
      restartPolicy: Always
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}

{{ end }}
