{{ if .Values.tangodb.enabled }}

{{ if .Values.tangodb.use_pv }}
{{ if .Values.minikube }}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "tango-base.name" . }}-tangodb-storage
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tango-base.labels" . | indent 4 }}
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ template "tango-base.name" . }}-tangodb-storage-{{ .Release.Name }}/
{{ end }}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "tango-base.name" . }}-tangodb-storage
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tango-base.labels" . | indent 4 }}
spec:
{{ if .Values.minikube }}
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
{{ else }}
  storageClassName: nfss1
  accessModes:
    - ReadWriteMany
{{ end }}
  resources:
    requests:
      storage: 1Gi
{{ end }}

{{ end }}