{{ if .Values.tangotest.enabled }}
---

apiVersion: v1
kind: Pod
metadata:
  name: {{ template "tango-base.name" . }}-{{ .Values.tangotest.component }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tango-base.labels" . | indent 4 }}
    component: {{ .Values.tangotest.component }}
    function: {{ .Values.tangotest.function }}
    domain: {{ .Values.tangotest.domain }}
    intent: {{ .Values.tangotest.intent }}
spec:
  initContainers:
  - name: check-databaseds-ready
    image: "{{ .Values.tangotest.image.registry }}/{{ .Values.tangotest.image.image }}:{{ .Values.tangotest.image.tag }}"
    imagePullPolicy: {{ .Values.tangotest.image.pullPolicy }}
    command:
      - /usr/local/bin/wait-for-it.sh
      - "{{ include "tango-base.dbservice-name" . }}:10000"
      - --timeout=30
      - --strict
      - --
      - echo databaseds ready
  containers:
  - name: tangotest
    image: "{{ .Values.tangotest.image.registry }}/{{ .Values.tangotest.image.image }}:{{ .Values.tangotest.image.tag }}"
    imagePullPolicy: {{ .Values.tangotest.image.pullPolicy }}
    command:
      - /usr/local/bin/TangoTest
      - test
    env:
    - name: TANGO_HOST
      value: "{{ include "tango-base.dbservice-name" . }}:10000"
    resources:
{{ toYaml .Values.tangotest.resources | indent 6 }}
  restartPolicy: Always
{{- with .Values.nodeSelector }}
  nodeSelector:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.affinity }}
  affinity:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.tolerations }}
  tolerations:
{{ toYaml . | indent 4 }}
{{- end }}

{{ end }}