{{ if .Values.vnc.enabled }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "tango-base.name" . }}-{{ .Values.vnc.component }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tango-base.labels" . | indent 4 }}
    component: {{ .Values.vnc.component }}
    function: {{ .Values.vnc.function }}
    domain: {{ .Values.vnc.domain }}
    intent: {{ .Values.vnc.intent }}
spec:
  type: NodePort
  ports:
  - name: vncport
    port: 5920
    protocol: TCP
{{ if .Values.vnc.nodeport_enabled }}
    nodePort: {{ .Values.vnc.nodeport_vnc }}
{{end}}
  - name: novncport
    port: 6081
    protocol: TCP
{{ if .Values.vnc.nodeport_enabled }}
    nodePort: {{ .Values.vnc.nodeport_novnc }}
{{end}}
  selector:
    app: {{ template "tango-base.name" . }}
    component: {{ .Values.vnc.component }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "tango-base.name" . }}-{{ .Values.vnc.component }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tango-base.labels" . | indent 4 }}
    component: {{ .Values.vnc.component }}
    function: {{ .Values.vnc.function }}
    domain: {{ .Values.vnc.domain }}
    intent: {{ .Values.vnc.intent }}
spec:
  selector:
    matchLabels:
      app: {{ template "tango-base.name" . }}
      component: {{ .Values.vnc.component }}
  serviceName: {{ template "tango-base.name" . }}-{{ .Values.vnc.component }}
  replicas:  {{ .Values.vnc.replicas }}
  template:
    metadata:
      labels:
        {{- include "tango-base.labels" . | indent 8 }}
        component: {{ .Values.vnc.component }}
        function: {{ .Values.vnc.function }}
        domain: {{ .Values.vnc.domain }}
        intent: {{ .Values.vnc.intent }}
    spec:
      containers:
      - name: vnc
        image: "{{ .Values.vnc.image.registry }}/{{ .Values.vnc.image.image }}:{{ .Values.vnc.image.tag }}"
        imagePullPolicy: {{ .Values.vnc.image.pullPolicy }}
        ports:
        - name: vncport
          containerPort: 5920
        - name: novncport
          containerPort: 6081
        env:
        - name: KUBE_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: HELM_RELEASE
          value: {{ .Release.Name }}
        - name: TANGO_HOST
          value: "{{- if .Values.tangoDatabaseDS }}{{ .Values.tangoDatabaseDS }}{{- else -}}{{ if .Values.databaseds.domainTag }}databaseds-{{ template "tango-base.name" . }}-{{ .Values.databaseds.domainTag }}{{- else }}databaseds-{{ template "tango-base.name" . }}-{{ .Release.Name }}{{- end }}{{- end }}:10000"
        resources:
{{ toYaml .Values.vnc.resources | indent 10 }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}

{{ end }}