{{ if .Values.vscode.enabled }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "tango-base.name" . }}-{{ .Values.vscode.component }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tango-base.labels" . | indent 4 }}
    component: {{ .Values.vscode.component }}
    function: {{ .Values.vscode.function }}
    domain: {{ .Values.vscode.domain }}
    intent: {{ .Values.vscode.intent }}
spec:
  type: NodePort
  ports:
  - name: vscodeport
    port: 22
    protocol: TCP
{{ if .Values.vscode.nodeport_enabled }}
    nodePort: {{ .Values.vscode.nodeport }}
{{end}}
  selector:
    app: {{ template "tango-base.name" . }}
    component: {{ .Values.vscode.component }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "tango-base.name" . }}-{{ .Values.vscode.component }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tango-base.labels" . | indent 4 }}
    component: {{ .Values.vscode.component }}
    function: {{ .Values.vscode.function }}
    domain: {{ .Values.vscode.domain }}
    intent: {{ .Values.vscode.intent }}
spec:
  selector:
    matchLabels:
      app: {{ template "tango-base.name" . }}
      component: {{ .Values.vscode.component }}
  serviceName: {{ template "tango-base.name" . }}-{{ .Values.vscode.component }}
  replicas:  {{ .Values.vscode.replicas }}
  template:
    metadata:
      labels:
        {{- include "tango-base.labels" . | indent 8 }}
        component: {{ .Values.vscode.component }}
        function: {{ .Values.vscode.function }}
        domain: {{ .Values.vscode.domain }}
        intent: {{ .Values.vscode.intent }}
    spec:
      containers:
      - name: vscode
        image: "{{ .Values.vscode.image.registry }}/{{ .Values.vscode.image.image }}:{{ .Values.vscode.image.tag }}"
        imagePullPolicy: {{ .Values.vscode.image.pullPolicy }}
        ports:
        - name: vscodeport
          containerPort: 22
        env:
        - name: KUBE_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: HELM_RELEASE
          value: {{ .Release.Name }}
        - name: TANGO_HOST
          value: {{ if .Values.tangoDatabaseDS -}} {{ .Values.tangoDatabaseDS }}:10000 {{- else -}} databaseds-tango-base-{{ .Release.Name }}:10000 {{- end }}
        resources:
{{ toYaml .Values.vscode.resources | indent 10 }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}

{{ end }}