---
suite: databaseds config
templates:
  - databaseds.yaml
tests:
  - it: should set TANGO_HOST environment variable to its own in-cluster hostname
    release:
      name: arbitrary-release
    asserts:
      - contains:
          path: spec.template.spec.containers[0].env
          content: 
            name: TANGO_HOST
            value: databaseds-tango-base-arbitrary-release:10000
        documentIndex: 1

