# Default values for HDB++ Archiver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"
minikube: true

enabled: true

system: SW-infrastructure
subsystem: archiver
telescope: SKA-mid

global:
  labels:
    app: ska-docker
  annotations:
    app.gitlab.com/app: CI_PROJECT_PATH_SLUG
    app.gitlab.com/env: CI_ENVIRONMENT_SLUG
  tango_host: databaseds-tango-base-test:10000
  environment_variables: []
  dsconfig:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-dsconfig
      tag: 1.2.5.1
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-itango
      tag: 9.3.1
      pullPolicy: IfNotPresent

dsconfig:
  configuration_file: data/configuration.json

hdbppdb:
  enabled: true
  use_pv: false
  component: db
  function: tango-archiver
  domain: tango-archiver
  intent: production
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: mariadb_hdbpp
    tag: 1.1.0
    pullPolicy: IfNotPresent
  db:
    rootpw: secret
    db: hdbpp
    user: tango
    password: tango
  resources:
    requests:
      cpu: 100m     # 100m = 0.1 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 1Gi
    limits:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 2Gi
  livenessProbe:
    enabled: false
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    enabled: false
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

deviceServers:
- name: arhiver-cm-archiver-test
  function: tango-archiver-service
  domain: archiver
  args:
  - "-c"
  - "./usr/local/bin/hdbppcm-srv 01"
  depends_on: 
  - host: archiver-hdbppdb-db:3306
  - device: sys/database/2
  environment_variables: 
  - name: HdbManager
    value: "archiving/hdbpp/confmanager01"
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-archiver
    tag: 1.0.0
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m     # 100m = 0.1 CPU
      memory: 128Mi # 128Mi = 0.125 GB mem
      ephemeral-storage: 512Mi
    limits:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 1Gi
- name: arhiver-es-archiver-test
  function: tango-archiver-service
  domain: archiver
  args:
  - "-c"
  - "./usr/local/bin/hdbppes-srv 01"
  depends_on: 
  - host: archiver-hdbppdb-db:3306
  - device: sys/database/2
  environment_variables: 
  - name: HdbManager
    value: "archiving/hdbpp/confmanager01"
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-archiver
    tag: 1.0.0
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m     # 100m = 0.1 CPU
      memory: 128Mi # 128Mi = 0.125 GB mem
      ephemeral-storage: 512Mi
    limits:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 1Gi

hdbppviewer:
  enabled: false
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: hdbpp_viewer
    tag: 1.10
    pullPolicy: IfNotPresent

nodeSelector: {}

affinity: {}

tolerations: []
