# Default values for HDB++ Archiver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"
enabled: true

system: SW-infrastructure
subsystem: archiver
telescope: SKA-mid

global:
  minikube: true
  tango_host: databaseds-tango-base-{{.Release.Name}}:10000

labels:
  app: ska-docker
annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG

dsconfig:
  configuration_file: data/configuration.json
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-dsconfig
    tag: 1.5.0
    pullPolicy: IfNotPresent

itango:
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-itango
    tag: 9.3.1
    pullPolicy: IfNotPresent

attributes2archive: 
- attributes:
    - "sys/tg_test/1/ulong_scalar"
    - "sys/tg_test/1/long64_scalar"
    - "sys/tg_test/1/long_scalar"
  polling_period: 1000
  period_event: 3000

archiver_image:
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-archiver
    tag: 1.0.0
    pullPolicy: IfNotPresent

hdbppdb:
  enabled: true
  use_pv: true
  storage_size: 100Gi
  cleaning_schedule: "* 6,18 * * *"
  component: db
  function: tango-archiver
  domain: tango-archiver
  intent: production
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: mariadb_hdbpp
    tag: 1.1.0
    pullPolicy: IfNotPresent
  db:
    rootpw: secret
    db: hdbpp
    user: tango
    password: tango
  resources:
    requests:
      cpu: 100m     # 100m = 0.1 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 1Gi
    limits:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 2Gi
  livenessProbe:
    enabled: false
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    enabled: false
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

wait_for_dsconfig:
  image:
    registry: "docker.io"
    image: "bitnami/kubectl"
    tag: "1.18.10"
    pullPolicy: "IfNotPresent"

deviceServers:
- name: arhiver-cm-archiver-test
  function: tango-archiver-service
  domain: archiver
  command: "./usr/local/bin/hdbppcm-srv"
  instances: ["01"]
  wait_for_dsconfig:
    image:
      registry: "{{.Values.wait_for_dsconfig.image.registry}}"
      image: "{{.Values.wait_for_dsconfig.image.image}}"
      tag: "{{.Values.wait_for_dsconfig.image.tag}}"
      pullPolicy: "{{.Values.wait_for_dsconfig.image.pullPolicy}}"
  depends_on: 
  - host: archiver-hdbppdb-db:3306
  - device: sys/database/2
  environment_variables: 
  - name: HdbManager
    value: "archiving/hdbpp/confmanager01"
  image:
    registry: "{{.Values.archiver_image.image.registry}}"
    image: "{{.Values.archiver_image.image.image}}"
    tag: "{{.Values.archiver_image.image.tag}}"
    pullPolicy: "{{.Values.archiver_image.image.pullPolicy}}"
  resources:
    requests:
      cpu: 100m     # 100m = 0.1 CPU
      memory: 128Mi # 128Mi = 0.125 GB mem
      ephemeral-storage: 512Mi
    limits:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 1Gi
- name: arhiver-es-archiver-test
  function: tango-archiver-service
  domain: archiver
  command: "./usr/local/bin/hdbppes-srv"
  instances: ["01"]
  wait_for_dsconfig:
    image:
      registry: "{{.Values.wait_for_dsconfig.image.registry}}"
      image: "{{.Values.wait_for_dsconfig.image.image}}"
      tag: "{{.Values.wait_for_dsconfig.image.tag}}"
      pullPolicy: "{{.Values.wait_for_dsconfig.image.pullPolicy}}"
  depends_on: 
  - host: archiver-hdbppdb-db:3306
  - device: sys/database/2
  environment_variables: 
  - name: HdbManager
    value: "archiving/hdbpp/confmanager01"
  image:
    registry: "{{.Values.archiver_image.image.registry}}"
    image: "{{.Values.archiver_image.image.image}}"
    tag: "{{.Values.archiver_image.image.tag}}"
    pullPolicy: "{{.Values.archiver_image.image.pullPolicy}}"
  resources:
    requests:
      cpu: 100m     # 100m = 0.1 CPU
      memory: 128Mi # 128Mi = 0.125 GB mem
      ephemeral-storage: 512Mi
    limits:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 1Gi

hdbppviewer:
  enabled: false
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: hdbpp_viewer
    tag: 1.10
    pullPolicy: IfNotPresent

nodeSelector: {}

affinity: {}

tolerations: []
