{{- /*
tango-util.secret-provider-class.tpl
Parameters:
- local (the local chart must include vaultAddress)
- name (of the SecretProviderClass)
- secrets array of objects composed by:
- secretPath (secret path in vault)
- list of env composed by:
- secretKey (secret key in vault)
- envName (environment variable to be set in the device server)
*/}}
{{ define "ska-tango-util.secret-provider-class-svc.tpl" }}

{{- $labels := coalesce .local.Values.global.labels .local.Values.labels "label:none" }}
{{- $annotations := coalesce .local.Values.global.annotations .local.Values.annotations }}
{{- $vaultAddress := coalesce .local.Values.global.vaultAddress .local.Values.vaultAddress }}

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .name }}
  namespace: {{ .local.Release.Namespace }}
{{- if $labels }}
  labels:
{{ toYaml $labels | indent 4 }}
{{- end }}
{{- if $annotations }}
  annotations:
{{ toYaml $annotations | indent 4 }}
{{- end }}
spec:
  provider: vault
  parameters:
    vaultAddress: "{{ $vaultAddress }}"
    roleName: "kube-role"
    objects: |
{{- range $secret := .secrets }}
{{- range $env := $secret.env }}
      - objectName: {{ $env.secretKey }}
        secretPath: {{ $secret.secretPath }}
        secretKey: {{ $env.secretKey }}
{{- end }}
{{- end }}
  secretObjects:
    - secretName: {{ .name }}
      type: Opaque
      data:
{{- range $secret := .secrets }}
{{- range $env := $secret.env }}
        - objectName: {{ $env.secretKey }}
          key: {{ $env.envName }}
{{- end }}
{{- end }}

{{- end }}
