{{ if .Values.enabled }}

{{ template "tango-util.configuration.tpl" . }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "attrconfig-configuration-{{ template "archiver.name" . }}-{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml .Values.global.labels | indent 4 }}
{{ if (.Values.global.annotations) }}
  annotations:
{{ toYaml .Values.global.annotations | indent 4 }}
{{ end }}
data:
  attribute2archive.json:
{{ (tpl (.Files.Glob "data/attribute2archive.json").AsConfig . ) | indent 2 }}
  configure_hdbpp.py:
{{ (tpl (.Files.Glob "data/configure_hdbpp.py").AsConfig . ) | indent 2 }}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: attrconfig-{{ template "archiver.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml .Values.global.labels | indent 4 }}
{{ if (.Values.global.annotations) }}
  annotations:
{{ toYaml .Values.global.annotations | indent 4 }}
{{ end }}
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      volumes:
      - name: configureattrconfig
        configMap:
          name: "attrconfig-configuration-{{ template "archiver.name" . }}-{{ .Release.Name }}"
      initContainers:
        - name: wait-for-devices
          image: "{{ .Values.global.dsconfig.image.registry }}/{{ .Values.global.dsconfig.image.image }}:{{ .Values.global.dsconfig.image.tag }}"
          imagePullPolicy: {{ .Values.global.dsconfig.image.pullPolicy }}
          command:
            - sh
          args:
            - -c
            - "retry --max=20 -- tango_admin --ping-device archiving/hdbpp/eventsubscriber01 && \
              retry --max=20 -- tango_admin --ping-device archiving/hdbpp/confmanager01"
          env:
          - name: TANGO_HOST
            value: {{ .Values.global.tango_host }}
      containers:
      - name: attrconfig
        image: "{{ .Values.global.itango.image.registry }}/{{ .Values.global.itango.image.image }}:{{ .Values.global.itango.image.tag }}"
        imagePullPolicy: {{ .Values.global.itango.image.pullPolicy }}
        command:
          - sh
        args:
          - -c
          - "/venv/bin/python data/configure_hdbpp.py \
              --cm=archiving/hdbpp/confmanager01 \
              --es=archiving/hdbpp/eventsubscriber01 \
              --attrfile=data/attribute2archive.json"
        env:
        - name: TANGO_HOST
          value: {{ .Values.global.tango_host }}
        volumeMounts:
          - name: configureattrconfig
            mountPath: /app/data
            readOnly: true
      restartPolicy: OnFailure

{{ end }}

