# Default values for tango-base.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"
minikube: true

labels:
  app: ska-docker
annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG

global:
  tango_host: databaseds-tango-base-{{.Release.Name}}:10000
  environment_variables: []
  dsconfig:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-dsconfig
      tag: 1.5.0
      pullPolicy: IfNotPresent
  # by setting this parameter we can disable the lower level sub-system tango-base, archiver and webjive
  # sub-system:
  #   tango-base:
  #     enabled: false
  #   archiver:
  #     enabled: false
  #   webjive: 
  #     enabled: false

tango-base:
  itango:
    enabled: true
  jive:
    enabled: false
  vnc:
    enabled: true
  vscode:
    enabled: true
  tangorest:
    enabled: true
  ingress:
    enabled: true
    hostname: tango-base.minikube.local
