# Default values for tango-base.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"
minikube: true

global:
  labels:
    app: ska-docker
  annotations:
    app.gitlab.com/app: CI_PROJECT_PATH_SLUG
    app.gitlab.com/env: CI_ENVIRONMENT_SLUG
  tango_host: databaseds-tango-base-test:10000
  environment_variables: []
  dsconfig:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-dsconfig
      tag: 1.2.5.1
      pullPolicy: IfNotPresent

tango-base:
  itango:
    enabled: true
  jive:
    enabled: false
  vnc:
    enabled: true
  vscode:
    enabled: true
  tangorest:
    enabled: true
  ingress:
    enabled: true
    hostname: tango-base.minikube.local

