{{ $databaseds_name := (split ":" .Values.global.tango_host)._0 }}
{{ $databaseds_port := (split ":" .Values.global.tango_host)._1 }}
{{ $tries := coalesce  .Values.global.tries 10}}
{{ $sleep := coalesce  .Values.global.sleep 5}}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ tpl ($databaseds_name | toString) . }}
  namespace: {{ .Release.Namespace }}
  labels:
    component: {{ .Values.databaseds.component }}
    function: {{ .Values.databaseds.function }}
    domain: {{ .Values.databaseds.domain }}
    intent: {{ .Values.databaseds.intent }}
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 4 }}
{{ if or (.Values.global.annotations) (.Values.annotations) }}
  annotations:
{{ toYaml (coalesce .Values.global.annotations .Values.annotations) | indent 4 }}
{{ end }}
spec:
  ports:
  - name: ds
    port: {{ $databaseds_port }}
  type: NodePort
  selector:
    component: {{ .Values.databaseds.component }}
    function: {{ .Values.databaseds.function }}
    domain: {{ .Values.databaseds.domain }}
    intent: {{ .Values.databaseds.intent }}
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 4 }}

---
## The LoadBalancer for external access
{{ if or (.Values.global.minikube) (.Values.global.exposeAllDS) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ tpl ($databaseds_name | toString) . }}-external
  namespace: {{ .Release.Namespace }}
  labels:
    component: {{ .Values.databaseds.component }}
    function: {{ .Values.databaseds.function }}
    domain: {{ .Values.databaseds.domain }}
    intent: {{ .Values.databaseds.intent }}
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 4 }}
{{ if or (.Values.global.annotations) (.Values.annotations) }}
  annotations:
{{ toYaml (coalesce .Values.global.annotations .Values.annotations) | indent 4 }}
{{ end }}
spec:
  ports:
  - name: ds
    port: {{ $databaseds_port }}
  type: LoadBalancer
  selector:
    component: {{ .Values.databaseds.component }}
    function: {{ .Values.databaseds.function }}
    domain: {{ .Values.databaseds.domain }}
    intent: {{ .Values.databaseds.intent }}
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 4 }}

{{ end }}
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ tpl ($databaseds_name | toString) . }}
  namespace: {{ .Release.Namespace }}
  labels:
    component: {{ .Values.databaseds.component }}
    function: {{ .Values.databaseds.function }}
    domain: {{ .Values.databaseds.domain }}
    intent: {{ .Values.databaseds.intent }}
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 4 }}
{{ if or (.Values.global.annotations) (.Values.annotations) }}
  annotations:
{{ toYaml (coalesce .Values.global.annotations .Values.annotations) | indent 4 }}
{{ end }}
spec:
  selector:
    matchLabels:
      component: {{ .Values.databaseds.component }}
      function: {{ .Values.databaseds.function }}
      domain: {{ .Values.databaseds.domain }}
      intent: {{ .Values.databaseds.intent }}
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 6 }}
  serviceName: {{ tpl ($databaseds_name | toString) . }}
  replicas: 1
  template:
    metadata:
      labels:
        component: {{ .Values.databaseds.component }}
        function: {{ .Values.databaseds.function }}
        domain: {{ .Values.databaseds.domain }}
        intent: {{ .Values.databaseds.intent }}
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 8 }}
    spec:
      containers:
      - name: databaseds
        image: "{{ .Values.databaseds.image.registry }}/{{ .Values.databaseds.image.image }}:{{ .Values.databaseds.image.tag }}"
        imagePullPolicy: {{ .Values.databaseds.image.pullPolicy }}
        command:
          - retry
          - --tries={{$tries}}
          - --sleep={{$sleep}}
          - --
          - /usr/local/bin/wait-for-it.sh
          - {{ template "ska-tango-base.name" . }}-{{ .Values.tangodb.component }}:3306
          - --timeout=60
          - --strict
          - --
          - /usr/local/bin/DataBaseds
          - "2"
          - -ORBendPoint
          - giop:tcp::{{ $databaseds_port }}
          - -ORBendPointPublish
          - giop:tcp:{{ tpl ($databaseds_name | toString) . }}:{{ $databaseds_port }}
        env:
          - name: MYSQL_HOST
            value: "{{ template "ska-tango-base.name" . }}-{{ .Values.tangodb.component }}:3306"
          - name: MYSQL_DATABASE
            value: "{{ .Values.tangodb.db.db }}"
          - name: MYSQL_USER
            value: "{{ .Values.tangodb.db.user }}"
          - name: MYSQL_PASSWORD
            value: "{{ .Values.tangodb.db.password }}"
        ports:
        - name: ds
          containerPort: {{ $databaseds_port }}
        {{- if .Values.databaseds.livenessProbe.enabled }}
        readinessProbe:
          tcpSocket:
            port: {{ $databaseds_port }}
          initialDelaySeconds: {{ .Values.databaseds.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.databaseds.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.databaseds.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.databaseds.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.databaseds.readinessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.databaseds.readinessProbe.enabled }}
        livenessProbe:
          tcpSocket:
            port: {{ $databaseds_port }}
          initialDelaySeconds: {{ .Values.databaseds.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.databaseds.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.databaseds.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.databaseds.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.databaseds.livenessProbe.failureThreshold }}
        {{- end }}
        resources:
{{ toYaml .Values.databaseds.resources | indent 10 }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
